### PR TITLE
Join libs team.

### PR DESCRIPTION
**Pull request by reitermarkus**
Split out from https://github.com/rust-embedded/wg/pull/727.

### CODE REVIEW

**Comment by reitermarkus** [comment]
This needs a team vote by the @rust-embedded/libs team:

- [ ] @Dirbaio
- [ ] @newAM

**Review by newAM — APPROVED** [review]
welcome! 👋

**Comment by reitermarkus** [comment]
@adamgreig, seems like you added and then immediately removed me again.

**Comment by adamgreig** [comment]
I think the Rust project automation did that to keep the teams in sync; once your PR to the teams repo gets merged, I think it will re-add you.

**Pull request merged**
