### PR TITLE
Form the triage team

### PR DESCRIPTION
**Pull request by japaric**
As RFC #136 states we'll create a triage team to keep PRs moving. The linked RFC describes the job
of the triage team. If you are interested in being part of the triage team leave a comment below.

### CODE REVIEW

**Comment by jamesmunns** [comment]
@japaric we should probably discuss this, as the triage team has not materialized.

**Comment by Disasm** [comment]
Sorry, I thought this is an issue, not PR. I'm interested in being part of the team.

**Comment by mathk** [comment]
I could give some help! You can add me.

**Comment by japaric** [comment]
Rebased and update. @mathk and @Disasm are the initial members of the triage team.

r? @Disasm

**Comment by japaric** [comment]
@rust-embedded/triage now exists and should have enough permissions to add labels to PRs

**Pull request merged**
