### PR TITLE
Update MSRV policy

### PR DESCRIPTION
**Pull request by adamgreig**
This PR updates our MSRV policy in line with RFC #523.

### CODE REVIEW

**Review by thalesfragoso — APPROVED** [review]
Great, thanks!

bors r+

**Comment by therealprof** [comment]
@adamgreig Do you have a good recipe to add scheduled builds to CI? Would be great to add that to our documented procedures as well.

**Comment by eldruin** [comment]
@therealprof you can add an schedule entry which uses cron syntax. For example:
```yaml
on: 
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * 1
```
(Taken from [here](https://github.com/eldruin/driver-examples/blob/1419cd2c32a204393a4040cad157e56c2f6cc692/.github/workflows/build.yml#L5))

**Comment by therealprof** [comment]
@eldruin Thanks, I was aware that can be done that way. I was hoping that someone had a refined version already worked out which we could massage into out docs (and all WG repos). 😅

**Pull request merged**
