### PR TITLE
Add myself to Tools team

### PR DESCRIPTION
**Pull request by adamgreig**
As discussed in today's meeting I'd like to apply for membership of the tools team. I'm interested in the ongoing svd2rust work especially and would be happy to help reviewing PRs there.

### CODE REVIEW

**Comment by thejpster** [comment]
Can someone remind me - are these join requests for anyone in the WG to approve, or only those
 on the team?

**Comment by hannobraun** [comment]
@thejpster 
> Can someone remind me - are these join requests for anyone in the WG to approve, or only those
> on the team?

I think it's the team: https://github.com/rust-embedded/wg/blob/master/rfcs/0136-teams.md#adding-new-members

**Comment by andre-richter** [comment]
Whoops, please disregard my vote then. Apologies.

**Pull request merged**
