### PR TITLE
I would like to join the RISC-V and HAL team.

### PR DESCRIPTION
**Pull request by MabezDev**
I'd like to join the RISC-V and HAL team, if you'd have me :).

### CODE REVIEW

**Comment by eldruin** [comment]
This needs a team vote by the @rust-embedded/risc-v team:

- [ ] @almindor 
- [ ] @Disasm 
- [ ] @dkhayes117 
- [ ] @romancardenas 

And from the @rust-embedded/hal team:

- [ ] @Dirbaio 
- [X] @eldruin 
- [ ] @ryankurte 
- [ ] @therealprof 

From my side, welcome aboard!

**Review by eldruin — APPROVED** [review]

**Comment by romancardenas** [comment]
Same here!

**Review by Dirbaio — APPROVED** [review]
welcome! :heart:

**Comment by almindor** [comment]
Welcome!

**Comment by jonathanpallant** [comment]
Don't forget https://github.com/rust-lang/team/blob/master/teams/wg-embedded-riscv.toml etc.

**Comment by adamgreig** [comment]
Welcome to the working group! :heart:

**Pull request merged**
