### PR TITLE
[RFC] design documents

### PR DESCRIPTION
**Pull request by vitiral**
RFC to start design documents for what we want out of the rust embedded ecosystem.

[Rendered](https://github.com/vitiral/rfcs-1/blob/design/0000-design.md)

### CODE REVIEW

**Comment by vitiral** [comment]
I am going to continue to work on an MVP for the initial design docs. This thread is intended to be a request for comment on the design docs themselves as well!

@japaric I am particularily interested in your thoughts.

**Comment by Goyapa** [comment]
@vitiral 
I like the overview [artifact](https://github.com/vitiral/artifact) gives for discussion and documenting a project like this site shows.
https://vitiral.github.io/rust-embedded-design/#artifacts/req-layers

But I have to say that I do not know any other tool, so I can`t compare.
A tool, written in Rust, for Rust developers... nice!

**Comment by thejpster** [comment]
As a stack engineer, I cant help but point out that Layer 1 is at the bottom...! I really like the idea of breaking systems apart in this manner though - it's what I do every day.

**Comment by jamesmunns** [comment]
There has not been any conversation on this in about a year and a half, and would like to nominate this RFC be closed.

If you would like this RFC to remain open, please provide updates and justification.

**Comment by japaric** [comment]
I am closing this PR, please feel free to open a new issue if you would like this discussed further.

**Pull request closed without merging**
