### PR TITLE
laanwj joining RISC-V team

### PR DESCRIPTION
**Pull request by laanwj**
Hello, I'd like to join the Rust RISC-V team!

I have various activity around RISC-V and Rust the last year:

- Contributed peripheral descriptions to [k210-pac](https://github.com/riscv-rust/k210-pac), and UART serial for [k210-hal](https://github.com/riscv-rust/k210-hal/)
- Wrote some [embedded demos in Rust](https://github.com/laanwj/k210-sdk-stuff) for the Maix Go Board, porting part of the Kendryte C SDK to Rust on the way
- Contributed to [rvsim](https://github.com/stephank/rvsim), a RV32G simulator in Rust
- Created [rust-riscv-disasm](https://github.com/laanwj/rust-riscv-disasm), a RISC-V disassembler in Rust

My primary interest in RISC-V is as a secure future architecture for bitcoin things. However, I'm also interested in advancing the state of Rust on RISC-V in general. I'm *relatively* new to Rust but really like the language and see it as the spiritual successor to C++.

Besides the MaixGo I have a SiFive Unleashed board and HiFive1 (both rev a and b) for testing on actual hardware.

@Disasm

### CODE REVIEW

**Comment by Disasm** [comment]
Yay! :tada: 

Could you also add a link to your GitHub account (a big list under the `Contact` section)?

**Comment by jamesmunns** [comment]
Welcome @laanwj!

* @bradjc
* @danc86
* @dvc94ch 

If you have a second to review, it would be appreciated!

**Comment by jamesmunns** [comment]
Look's like we've hit the voting majority! I'll add @laanwj to the organization, @nastevens could you please reach out and add them to the risc-v mailing list?

bors r+

**Comment by laanwj** [comment]
Thanks everyone ! I'm honored to have joined the team :tada:

**Comment by Disasm** [comment]
Could someone add @laanwj to the RISC-V team too? @jamesmunns, @japaric, @dvc94ch?

**Comment by therealprof** [comment]
@Disasm Done but we'll probably need to add them in a few more places, too.

**Comment by Disasm** [comment]
@therealprof Thanks!

**Comment by nastevens** [comment]
> @nastevens could you please reach out and add them to the risc-v mailing list?

@laanwj I've added the email address visible from your GitHub profile to the risc-v mailing list `risc-v at teams dot rust-embedded dot org`. If that's not right, please let us know at `infrastructure at teams dot rust-embedded dot org`

**Pull request merged**
