### PR TITLE
Add hdoordt to resources team

### PR DESCRIPTION
**Pull request by hdoordt**
I'd like to get started with touching up the discovery book, as well as other learning resources that are maintained by the resources team.

Pending approval from (IIUC):

- [x] [@adamgreig]
- [x] [@eldruin]
- [ ]  [@hargoniX]
- [x] [@jamesmunns]
- [ ] [@therealprof]

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Thank you!

Please could you update the PR so your name is in alphabetical order in the team and also add the link to your profile in the long list at the bottom of the file?

**Review by adamgreig — APPROVED** [review]

**Review by jamesmunns — APPROVED** [review]
Welcome aboard!

**Review by nastevens — APPROVED** [review]

**Review by eldruin — APPROVED** [review]
Welcome aboard!

**Comment by adamgreig** [comment]
welcome to the team!

**Pull request merged**
