### PR TITLE
Add myself to the HAL team

### PR DESCRIPTION
**Pull request by eldruin**
@therealprof approached be about this.
I would be glad to help with `embedded-hal` and anything else related.

### CODE REVIEW

**Comment by therealprof** [comment]
Thank you for your interest in joining the team.

I think your contributions to embedded Rust, especially your many high quality drivers, excellent blog posts and contributions to WG-handled crates really speak for themselves.

**Comment by therealprof** [comment]
@ithinuel @ryankurte Any concerns? Can I ask for your approval?

**Comment by ryankurte** [comment]
sounds great to me!

**Comment by therealprof** [comment]
Since we have team majority approval and no concerned I'm going to merge this.

Welcome to the team @eldruin!

**Comment by eldruin** [comment]
Thank you! :)

**Pull request merged**
