### PR TITLE
Add @newAM to the Cortex-M team

### PR DESCRIPTION
**Pull request by newAM**
As discussed in the rust-embedded meeting today; see [this comment](https://github.com/rust-embedded/cortex-m/pull/355#issuecomment-1052351035) for additional context.

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]

**Review by burrbull — APPROVED** [review]

**Review by thejpster — APPROVED** [review]

**Review by therealprof — APPROVED** [review]

**Comment by therealprof** [comment]
I notice we have 3 out of 4 @rust-embedded/cortex-m team approvals. Can we make that decision unanimous, @thalesfragoso? ;)

**Review by thalesfragoso — APPROVED** [review]
Sorry, I completely missed the notification, my bad. Welcome to the team!

**Comment by adamgreig** [comment]
bors r+

welcome aboard!

**Pull request merged**
