### PR TITLE
notes on highfive

### PR DESCRIPTION
**Pull request by japaric**
This PR adds some notes about how to use highfive and a bit of how it works.

For now, highfive has been enabled for the cortex-m repository, but we can send
a PR to rust-lang-nursery/highfive to enable it on other rust-embedded repos.
There's one extra step, which I can do, after the PR lands

Questions:

- Do we want to use highfive on *all* the rust-embedded repos?

- Do we want to do that ^ in one sweep or incrementally? e.g. one team at a time

cc @rust-embedded/all

### CODE REVIEW

**Comment by Disasm** [comment]
I think that Highfive is awesome and using it on %reponame% is not worse than what we have already. At least I'd like to try it on riscv-team repos since I almost feel guilty about kicking @dvc94ch every time for my PRs.

**Comment by dvc94ch** [comment]
@Disasm No reason to feel guilty. To me it makes absolutely no difference if highfive does it or you do. Sometimes the github notifications get lost or I forget or when multiple PR's get opened on different repos I might not realize that there are multiple PRs. If you want to kick someone kick them, you don't need a bot to do your dirty work =P

**Comment by posborne** [comment]
embedded-linux team is on board I believe (CC @nastevens).  I often miss/forget about notifications and like to be able to click through reviews which have been requested of me through https://github.com/pulls/review-requested in order to catch up on stuff I might have forgotten about a few times a week.

**Comment by japaric** [comment]
I will do a PR to update the highfive configuration next week; if a team wants
to use highfive in *all* their repositories please check the boxes below -- I
will enable highfive if a majority of the team has approved.

- cortex-a
  - [ ] @raw-bin
  - [ ] @andre-richter
  - [ ] @parched
  - [ ] @wizofe

- cortex-m
  - [ ] @adamgreig
  - [ ] @korken89
  - [ ] @thejpster
  - [ ] @therealprof
  - [ ] @ithinuel

- cortex-r
  - [ ] @paoloteti

- embedded-linux
  - [x] @posborne
  - [x] @nastevens

- hal
  - [ ] @hannobraun
  - [ ] @ryankurte
  - [ ] @thejpster
  - [ ] @therealprof
  - [ ] @ithinuel

- infrastructure
  - [ ] @nastevens
  - [ ] @ryankurte

- msp430
  - [ ] @pftbest
  - [ ] @cr1901
  - [ ] @awygle

- resources
  - [ ] @adamgreig
  - [ ] @ryankurte
  - [ ] @korken89
  - [ ] @thejpster
  - [ ] @jamesmunns
  - [ ] @therealprof

- riscv
  - [ ] @danc86
  - [ ] @dvc94ch
  - [ ] @disasm
  - [ ] @bradjc

- tools
  - [ ] @ryankurte
  - [ ] @emilgardis
  - [ ] @therealprof

If you would like to *not* enable highfive on a specific repository let me know below.

**Comment by hannobraun** [comment]
I don't currently have an opinion one way or the other, and since I've had very little bandwidth for WG things for a while now, I don't want a lack of vote to influence the decision for the HAL team. I've marked myself in the list as having abstained, so please don't count me as an against vote.

**Comment by jamesmunns** [comment]
@ryankurte you checked your name for all of the projects except resources. Was this intentional?

**Comment by japaric** [comment]
Highfive has been enabled for all the repositories under the cortex-m, cortex-r, embedded Linux, HAL, infrastructure, resources and tools teams. For further tweaking (e.g. removing yourself from the rotation, or adding a new repo) send a PR to rust-lang-nursery/highfive. You can use rust-lang-nursery/highfive#195 as a reference.

bors r+

**Pull request merged**
