### PR TITLE
theJPster awakes

### PR DESCRIPTION
**Pull request by thejpster**
I'd like to come out of hibernation and rejoin the Cortex-M team. As I also have a StarFive/BeagleV I thought it might also be useful if I joined the RISC-V team.

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Welcome back!

**Review by jamesmunns — APPROVED** [review]
Woooo!

**Review by therealprof — APPROVED** [review]
Nice. To join the RISC-V team the team will need to approve.

@almindor or @Disasm?

**Review by thalesfragoso — APPROVED** [review]
Nice to have you back !!

**Review by eldruin — APPROVED** [review]
Nice! welcome back!

**Review by ryankurte — APPROVED** [review]
🎉

**Review by cr1901 — APPROVED** [review]

**Review by Disasm — APPROVED** [review]
Glad to see you in the RISC-V team!

**Review by burrbull — APPROVED** [review]

**Comment by therealprof** [comment]
Excellent. Welcome back @thejpster! 🎉

bors r+

**Pull request merged**
