### PR TITLE
add cortex-r, dcc and panic-dcc to crates maintained by the cortex-r team

### PR DESCRIPTION
**Pull request by japaric**
DCC (Debug Communication Channel) is a debug interface similar to Cortex-M's
ITM.

r? @rust-embedded/cortex-r

### CODE REVIEW

**Comment by thejpster** [comment]
Oh. Where I'm from, DCC is the official standard for digitally controlling model trains. Can we call this `cortex-dcc` or `arm-dcc` or `debug-comm-channel`, or something?

**Comment by paoloteti** [comment]
**DCC = Dual-Clock Comparator** on lockstep ARM devices. So, even if DCC is vendor specific and not from ARM, `arm-dcc` may be is not the best name too.

**Comment by eddyp** [comment]
But this code would support the arm/cortex implementation of dcc, so it should be OK, right?
BTW, I consider it a design flaw that cargo has a flat name space since name collisions can occur really easily. For instance, there is a git tool that predates Linus' vcs...

**Comment by japaric** [comment]
Renamed dcc to arm-dcc in the README.

@paoloteti you'll have to approve this PR again.

**Comment by japaric** [comment]
sudo
bors r=paoloteti

**Comment by japaric** [comment]
The arm-dcc repository has been moved into the org: https://github.com/rust-embedded/arm-dcc

**Pull request merged**
