### PR TITLE
Add Bart Massey to Resources team

### PR DESCRIPTION
**Pull request by BartMassey**
Want to help with documentation.

### CODE REVIEW

**Review by jamesmunns — APPROVED** [review]
Welcome!

**Review by nastevens — APPROVED** [review]

**Review by burrbull — APPROVED** [review]

**Review by adamgreig — APPROVED** [review]
Welcome!

**Review by reitermarkus — APPROVED** [review]

**Review by MabezDev — APPROVED** [review]
Welcome!

**Comment by BartMassey** [comment]
:heart:

**Pull request merged**
