### PR TITLE
Request to join the RISC-V working group

### PR DESCRIPTION
**Pull request by romancardenas**
@dkhayes117 invited me to join the RISC-V working group and asked me to officially request membership with this PR. It would be my pleasure to join you!

### CODE REVIEW

**Comment by eldruin** [comment]
This needs a team vote by the @rust-embedded/risc-v team:

- [ ] @almindor 
- [ ] @Disasm 
- [ ] @dkhayes117

**Review by dkhayes117 — APPROVED** [review]
+1 👍🙂

**Comment by almindor** [comment]
Happy to have your on board! We need more people on deck as RISCV is getting more popular and most of us are fairly busy/casual.

**Review by almindor — APPROVED** [review]

**Comment by dkhayes117** [comment]
@eldruin I think this is good to merge now having a majority vote?

**Pull request merged**
