### PR TITLE
Step down from the core team and nominate adamgreig

### PR DESCRIPTION
**Pull request by jamesmunns**
So, we don't generally have a process for changing of the guard for the core team, but I think this is a healthy time to blaze some trails!

Due to scheduling and availability issues around [Ferrous Systems](https://ferrous-systems.com)' work on [OxidizeConf](https://oxidizeconf.com/) and [Sealed Rust](https://ferrous-systems.com/blog/sealed-rust-the-pitch/), I see myself being more and more busy over the coming months. For this reason, I plan to step down from the Core team, but remain on the Resources team.

Because it is important to have three people on the core team (to avoid deadlocked decisions), I'd also like to simultaneously nominate @adamgreig to replace me. In general, I'll plan on stepping down once a replacement is approved by @rust-embedded/all, whoever it is, but I think Adam would be an excellent choice, as one of the longest active members, a core maintainer of stm32-rs (probably the most active family of chip support groups in Rust), and an overall helpful and supportive member of the WG team!

I'll still be around to help out, but I think it's healthy for the embedded-wg to have a change of hands occasionally! Thanks to everyone who has helped make the working group what it is today :)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Thanks for all your work, James!

**Comment by therealprof** [comment]
Thanks for your hard work on this, James! Much appreciated.

I do fully concur and support the nomination of Adam Greig.

**Comment by adamgreig** [comment]
I won't be voting on this but wanted to confirm I'm very happy to join the core team, and also to join in thanking James for the huge amount of time and effort he's put in to running the WG. Thanks James!

**Comment by therealprof** [comment]
After adjusting the membership list I notice 12 approvals out of 19 votes with no raised objections.

Welcome to the core team @adamgreig 🎉 and thanks for all hard work @jamesmunns ❤️ !

bors r+

**Pull request merged**
