### PR TITLE
[RFC] Vote for new chat platform

### PR DESCRIPTION
**Pull request by jamesmunns**
This is still a work in progress.

[Rendered](https://github.com/rust-embedded/wg/blob/chat-vote/rfcs/0000-chat-vote.md)

CC @therealprof

### CODE REVIEW

**Comment by therealprof** [comment]
@IGBC How do you mean?

> The method this would work is by putting each candidate in its own post in a GH issue

I'll replace `GH` by `GitHub` for more clarity. Does that rectify your concern?

**Comment by jamesmunns** [comment]
Hello @rust-embedded/all,

I'd like to put this RFC up for review. If you could please make any comments on this RFC as soon as possible, it would be appreciated. Once we have had a chance to have feedback, we can put this up for an actual RFC vote.

**Comment by jamesmunns** [comment]
We have reached 10 approvals, which is >= 33%, and this has been open for a week. Merging with acceptance.

**Comment by therealprof** [comment]
CC https://github.com/rust-embedded/wg/issues/357

**Pull request merged**
