### PR TITLE
Add myself to the linux embedded team

### PR DESCRIPTION
**Pull request by ryankurte**
so i can help triage and move some of the outstanding PRs.

cc. @rust-embedded/embedded-linux

### CODE REVIEW

**Comment by ryankurte** [comment]
@rust-embedded/core could one of y'all action this please? ^_^

**Comment by therealprof** [comment]
@ryankurte Done. Guess I'll also need to add you to bors.

**Comment by ryankurte** [comment]
thanks ^_^

**Comment by ryankurte** [comment]
hmmm, i guess the same for crates.io publishing @posborne ?

**Comment by therealprof** [comment]
Uhm, I theory I shouldn't have to do anything but I just noticed the bors configuration is still using the HAL team as owner... ;)

**Comment by posborne** [comment]
> hmmm, i guess the same for crates.io publishing @posborne ?

There's a few individual crates where I need to go through and add the org following the post-transfer checklist item: https://github.com/rust-embedded/wg/blob/master/ops/post-transfer.md#cratesio.  Crates like sysfs_gpio predate the wg as the org is something I created back in the day which hosted a few of the linux stuff before it was handed off for grander designs.

I'll go through and add the linux team as owners on some crates, let me know if you run into one I have missed.

**Pull request merged**
