### PR TITLE
Add @rmsyn to RISC-V team

### PR DESCRIPTION
**Pull request by rmsyn**

### CODE REVIEW

**Comment by romancardenas** [comment]
CC @rust-embedded/riscv 

I vote yes. Your work during the last months is appreciated!

**Review by romancardenas — APPROVED** [review]

**Comment by BartMassey** [comment]
@rmsyn Welcome! Sorry for the slow merge.

**Comment by eldruin** [comment]
@adamgreen Could you please do the rest of operations necessary for this?

**Comment by romancardenas** [comment]
@adamgreig hi! I noticed @rmsyn is not part of the @rust-embedded/riscv team yet. Can you please update this?

**Pull request merged**
