### PR TITLE
Add @sirhcel to Linux team

### PR DESCRIPTION
**Pull request by sirhcel**
@eldruin invited me to join the Linux team. I would love to and here I am.

### CODE REVIEW

**Comment by eldruin** [comment]
This needs a team vote by the @rust-embedded/embedded-linux team:

- [ ] @eldruin
- [ ] @nastevens 
- [ ] @posborne  
- [ ] @ryankurte

**Review by eldruin — APPROVED** [review]
@sirhcel has shown outstanding dedication and expertise in his work on [serialport-rs](https://github.com/serialport/serialport-rs), which is why I have invited him to join us.
Welcome aboard!

**Review by nastevens — APPROVED** [review]

**Comment by nastevens** [comment]
Welcome aboard!

**Review by posborne — APPROVED** [review]

**Comment by adamgreig** [comment]
Welcome to the working group, @sirhcel!

**Pull request merged**
