### PR TITLE
discovery book triage rfc version 2

### PR DESCRIPTION
**Pull request by BartMassey**
This supersedes #759 .

### CODE REVIEW

**Review by therealprof — COMMENTED** [review]
Very much in favour of this.

**Review by eldruin — APPROVED** [review]
Sounds good to me, thank you for your work!

**Review by adamgreig — APPROVED** [review]

**Comment by adamgreig** [comment]
- [x] [@adamgreig](https://github.com/adamgreig)
- [x] [@bartmassey](https://github.com/BartMassey)
- [x] [@eldruin](https://github.com/eldruin)
- [ ] [@hargoniX](https://github.com/hargoniX)
- [ ] [@hdoordt](https://github.com/hdoordt)
- [ ] [@jamesmunns](https://github.com/jamesmunns)
- [x] [@therealprof](https://github.com/therealprof)

**Comment by BartMassey** [comment]
I will go ahead and merge this without waiting for @hdoordt . I think he'd approve :grinning:.

Thanks everybody!

**Pull request merged**
