### PR TITLE
Rename to embedded-alloc

### PR DESCRIPTION
**Pull request by Jzow**
CC [#56](https://github.com/rust-embedded/embedded-alloc/pull/56).

### CODE REVIEW

**Comment by reitermarkus** [comment]
As I already asked in https://github.com/rust-embedded/embedded-alloc/pull/56#discussion_r1041727500: Should this be maintained by the HAL team now that it is not specific to Cortex-M anymore?

**Comment by Jzow** [comment]
> Should this be maintained by the HAL team now that it is not specific to Cortex-M anymore?

@adamgreig  @eldruin @dirbaio , Is it necessary to re enable the RFC process?

**Comment by eldruin** [comment]
From an outsider's perspective, I agree it may make sense to move it to the HAL team.
Let's discuss this in tomorrow's meeting.

**Review by eldruin — APPROVED** [review]
We agreed to keep it maintained by the cortex-m at least for the time-being in the last two weekly meetings so let's merge this as-is.
Thank you!
bors r+

**Pull request merged**
