### PR TITLE
Fix ithinuel's link

### PR DESCRIPTION
**Pull request by jamesmunns**
Fixed the link for @ithinuel

### CODE REVIEW

**Comment by japaric** [comment]
We have had markdown errors before. Would it make sense to check the markdown syntax in the CI? Does such a markdown checker even exist?

**Comment by korken89** [comment]
Maybe https://github.com/mike42/mdcheckr ?

**Comment by korken89** [comment]
I gave `mdcheckr` a try and it works quite nicely (on my trustflight project):

```
$ mdcheckr README.md                                                                                                         [12:52:11]
Checking README.md ..
- Link https://travis-ci.org/korken89/trustflight_firmware [ OK ]
- Link https://github.com/korken89/kfly_firmware [ OK ]
- Link https://github.com/japaric/cortex-m-rtfm [ OK ]
- Link https://github.com/korken89/crect [ OK ]
- Link https://tools.ietf.org/html/draft-ietf-pppext-cobs-00 [ OK ]
- Link https://github.com/korken89/trustflight_hardware [ OK ]
- Link https://github.com/korken89 [ OK ]
- Link LICENSE-APACHE [ OK ]
- Link http://www.apache.org/licenses/LICENSE-2.0 [ OK ]
- Link LICENSE-MIT [ OK ]
- Link http://opensource.org/licenses/MIT [ OK ]
- Image https://travis-ci.org/korken89/trustflight_firmware.svg?branch=master [ OK ]
```

**Comment by korken89** [comment]
Any link to crates.io give a false positive, but I opened an issue for it: https://github.com/mike42/mdcheckr/issues/17

**Comment by korken89** [comment]
I fixed and PRed it (https://github.com/mike42/mdcheckr/pull/18), if it is merged it is working on all crates I tested.

**Pull request merged**
