### PR TITLE
Join HAL team.

### PR DESCRIPTION
**Pull request by reitermarkus**
Split out from https://github.com/rust-embedded/wg/pull/727.

### CODE REVIEW

**Comment by reitermarkus** [comment]
This needs a team vote by the @rust-embedded/hal team:

- [ ] @eldruin
- [ ] @ryankurte
- [ ] @Dirbaio
- [ ] @therealprof
- [ ] @MabezDev

**Comment by eldruin** [comment]
Thank you for your willingness to join the HAL team.
However, I have not seen any contributions by you to the HAL repository.

**Comment by reitermarkus** [comment]
> I have not seen any contributions by you to the HAL repository.

Understandable, given it's mostly contributions to other repos and quite a humble list with a 50% success rate of being merged

- https://github.com/rust-embedded/critical-section/pull/13
- https://github.com/rust-embedded/critical-section/pull/26
- https://github.com/rust-embedded/embedded-hal/pull/402
- https://github.com/rust-embedded/nb/pull/45

plus the occasional drive-by review.

**Comment by jannic** [comment]
I'd propose to close this ticket due to inactivity. It can always be opened again if desired.
https://github.com/rust-embedded/wg/pull/729 was merged, so its not like @reitermarkus is dropped from the WG.

**Pull request closed without merging**
