### PR TITLE
Add [@adamhott] to resources team

### PR DESCRIPTION
**Pull request by adamhott**
I've contributed to the new Discovery Book (my chapter is being added) as well as updated information on probe-rs in the documentation.

This is part of the documentation efforts of the resources group, so I think it makes sense to add me at this point.

I have more documentation efforts in mind, such as a proposal that I'm working on.

Please add me, thanks!

### CODE REVIEW

**Comment by Emilgardis** [comment]
@rust-embedded/resources

**Comment by adamhott** [comment]
This is the proposal I referred to above. https://github.com/adamhott/rust-spot-wg-proposal

**Comment by CodingInGreen** [comment]
**Exchange with Paul Lenz regarding Rust Foundation Grants:**

-------------------------------------------------------------------

**Paul Lenz**

Hi there

It can be be supporting the general goals and contributions towards the Working Group (in retrospect we should probably have called them "Project Member Fellowships" to avoid confusion on this point.

Kind regards

Paul

----------------------------------------------------------------------

**Adam Hott**

    Thanks Paul,

    For the Project Fellowship, does the project for the fellowship have to be within it's own project within the Working Group?

    Or can the project for the fellowship support the general goals and contributions toward the Working Group?

    Thanks,
    Adam

--------------------------------------------------------------------

**Paul Lenz**

     Hi there

    Many thanks for you email, hopefully this will answer your question:

     - Project Goal Fellowships are narrow in scope, in that they must been working to achieve one of the Rust Project Goals - https://rust-lang.github.io/rust-project-goals/2024h2/accepted.html - these grants are open to anyone, not just members of Teams/Working Groups

     - The Project Fellowships are broader in scope, in that the applicant proposes what it is they wish to work on, however these Fellowships are limited to Team/Working Group members.

     Kind regards

     Paul

------------------------------------------------------------------------

**Adam Hott**

         Hello,

         I recently attended an Embedded Devices Working Group meeting to run my rough draft for a grant proposal by them, for consideration to submit my proposal for a Rust Foundation Grant.

         The group had some questions:

             One person commented that in the past the grants, that for the grants that were accepted, their scope was more open and flexible, but now the grants being awarded are more narrowly scoped. Is that true?
             One person commented that the Rust Foundation Grant organization is looking for ideas on the types of grants to offer, and it's more flexible, which is the opposite of the other person's comments. Which is the case?
             Is it true that an added requirement for consideration for a Grant this year is that the person submitting the proposal must be a member of a Rust Team or a Rust Working Group? Is there any flexibility on this item?
             One person commented that its unfortunate that the grants the foundation is offering are now contingent on supporting Team or Working Group projects, and not generally available. Is it true that grants are only allocated for Official Projects sponsored by Teams or Working Groups?
          The general consensus was that my project proposal would be useful to the Rust Community and the Embedded Devices Working Group and supports the goals of the Rust Community and Embedded Devices Working Group, but it does not fit neatly into a formal project for the Embedded Devices Working Group to make a new category for. Will this limit my ability to make a proposal?

         Thank you,

         Adam Hott

**Review by eldruin — APPROVED** [review]
Welcome aboard!

**Review by jamesmunns — COMMENTED** [review]
At this moment, I am not personally comfortable approving this (but also not currently raising an objection). My reasons behind this are twofold:

First, I'm not personally familiar enough with Adam's docs/resources contributions, and his level of familiarity with things to a suitable level to be able to review PRs and make significant changes. Perhaps someone else could comment on that, if they are more familiar.

Second, I am somewhat uncomfortable at the timing and focus of being added to the WG, as it seems to be oriented towards checking a box for the Project Fellowship grant, particularly for a proposed project that is currently outside of the scope of the WG. In my understanding, this group of grants is aimed at supporting *existing* members working on *existing* or at least *agreed upon* work. While I do think that **if fully realized**, the proposed project would be a good reference, I'm not personally certain it is something that fits the scope of the WG's efforts and goals.

I appreciate Adam's excitement, and would love to see continued contributions to efforts like the discovery book rewrite, at which point I'd be willing to reconsider. But as of today, I am not comfortable with approving this PR.

**Comment by CodingInGreen** [comment]
| Handle      | Name                 | Vote                                |
|-------------|----------------------|-------------------------------------|
| hargonix    | Henrik Vöving        | abstain                             |
| jamesmunns  | James Munns          | abstain by not raising an objection or no vote?|
| eldruin     | Diego Barrios Romero | yes                                 |
| adamgreig   | Adam Greig           |                                     |
| hdoordt     | Henk Oordt           |                                     |
| therealprof | Daniel Egger |                                        |
| bartmassey | Bart Massey |                                       |

**Comment by jamesmunns** [comment]
@adamhott I am currently abstaining, to hear feedback from others.

**Comment by BartMassey** [comment]
I concur with @jamesmunns  well-reasoned comments. @adamhott we really value your enthusiasm and willingness to help, but I think we need a bit more of a record of accepted contributions before adding you. Hope this won't discourage you from continuing to PR and help out!

**Comment by CodingInGreen** [comment]
> I concur with @jamesmunns well-reasoned comments. @adamhott we really value your enthusiasm and willingness to help, but I think we need a bit more of a record of accepted contributions before adding you. Hope this won't discourage you from continuing to PR and help out!

Hi Bart, no worries. If you concur with James, would you consider from abstaining rather than a hard no regarding your vote, as James had concerns but didn't give an objection?

**Comment by adamhott** [comment]
> At this moment, I am not personally comfortable approving this (but also not currently raising an objection). My reasons behind this are twofold:
> 
> First, I'm not personally familiar enough with Adam's docs/resources contributions, and his level of familiarity with things to a suitable level to be able to review PRs and make significant changes. Perhaps someone else could comment on that, if they are more familiar.
> 
> Second, I am somewhat uncomfortable at the timing and focus of being added to the WG, as it seems to be oriented towards checking a box for the Project Fellowship grant, particularly for a proposed project that is currently outside of the scope of the WG. In my understanding, this group of grants is aimed at supporting _existing_ members working on _existing_ or at least _agreed upon_ work. While I do think that **if fully realized**, the proposed project would be a good reference, I'm not personally certain it is something that fits the scope of the WG's efforts and goals.
> 
> I appreciate Adam's excitement, and would love to see continued contributions to efforts like the discovery book rewrite, at which point I'd be willing to reconsider. But as of today, I am not comfortable with approving this PR.

I'd like to respond to the two points mentioned** @jamesmunns:

## Point One

#### I have contributed to the resources groups efforts with the Discovery Book, I spent a whole weekend writing a chapter for that, and have helped folks who had questions in the matrix chat room. I've also had PRs accepted such as for embedded-tls and I believe it was esp-hal. I attend nearly every Working Group meeting on Tuesday, and even travelled to meet with the Working Group to discuss initiatives such as the Discovery Book. As far as my capabilities to write documents, a book is a document and I have written one that is available on Amazon: 

[Adam Hott's Book](https://www.amazon.com/Codey-Toads-Computer-Game-Adventure-ebook/dp/B0CKQCHWRT/ref=sr_1_1?crid=2C8IO0TJDQ0DI&dib=eyJ2IjoiMSJ9.LrJPfPxCr3K4leFA6ghs7xPxPhlXc1MRtX5dcZKxKz4j64yVlgzwfDcppGR4JADwHxO4btEXh7rjF5yOGbI89N1NdVu_q23BQ9VEeYmu1fJmqKqLPobi3JpAQepU7XeyqB6QtGGI7AbWiapKw3SCOro3wDAQ0oSm41OVm7BCiSuZlkvq7n3lEvluafvoyyZXWCr2TmlYsE8yo092b_5uRx1YPQIsQCBBdvZzyYy0Dlo.MxJ4wnPu9zJ-eMQa4zFBJnNVNugoldgP3RS4CDDtLEs&dib_tag=se&keywords=adam+hott&qid=1722452875&sprefix=adam+hot%2Caps%2C207&sr=8-1)

I also would like to speak to the capabilities and experience question. I am currently an employed Embedded Engineer. But I think the question you ask speaks to the spirit of the Working Group, as is defined here: https://github.com/rust-embedded/wg

**In the help wanted section:**  
    
    "In some cases you may not even need previous embedded experience or access embedded hardware to help us out so don't let that discourage you from checking out our help wanted issues."


**two bullet points down**

    "You can collaborate with the maintenance and development of these projects by becoming a project collaborator (consult with the team that owns the project) or by [joining](https://github.com/rust-embedded/wg/blob/master/rfcs/0136-teams.md#adding-new-members) the team."

## Point Two

    I have been asking to be added as a member of the Working Group before the idea for this project was ever formed. My idea for this project was to potentially commercialize it, but since the Working Group has been so wonderful and helpful that I actually learned enough to become gainfully employed in the area, and when I learned of the open for Project Proposals recently, I thought it would be a nice way to pay back the community that helped me so much. If the proposal were to be accepted, I will have transferred my potential commercial interests to an effort to contribute back to the rust community and the working group. Joining the working group has been something on my mind for a long time, Adam Greig probably remembers me asking over and over if I can be added as I want to make an impact. To the point of the if this project fits the Working Groups goals, we discussed this in the meeting on 7-30-2024 and I thought there was general consensus that this project, while not a valid project to add to the Working Group agenda, would further benefit the rust and embedded community. And per Pauls email, it's not a requirement that my proposal project for the Rust Foundation to be accepted as a project for the Working Group. It's more relaxed than that. And the scope is more broad for Projects Proposals. As far as Project Proposals being for existing Working Group members, that is the point if this PR. Add me to the Working Group first, then I will be an existing member of the working group supporting the effort to rewrite the Discovery Book, then I am a member of the working group working on an ongoing effort. Thus the right to submit a proposal.

**Comment by hdoordt** [comment]
I generally agree with @jamesmunns and @BartMassey. Furthermore, given the doubt others in the WG have about this proposal and me having been a member for such a short period of time, I'll abstain from voting on this. Best of luck, @adamhott !

**Comment by adamhott** [comment]
It's impossible given the rules for voting, for me now to be approved. I want to thank everyone for their comments and feedback. I am a business professional and while it was a bit of an emotional rollercoasters as eldruin immediately approved the PR before I full knew the voting rules and thought I would be welcomed to join, I do understand about process and the reasons for proper processes. No hard feelings to anyone here for their votes either way. I hope to remain friendly with everyone and continue to be involved at some level with the Working Group. Thank you for your time! Cheers, Adam

**Comment by adamgreig** [comment]
Thank you for your work on the discovery book and your application to join the resources team, @adamhott!

To echo @BartMassey's sentiment, I really appreciate your dedication and contributions so far, but it's not yet at the stage where I feel that you're ready to be reviewing and managing other contributions to the books and other repos the resources team maintains. I also hope this doesn't discourage you from continuing to help out with the new discovery book work, and hopefully we can revisit this another time!

I'll close this PR now, but anyone is welcome to leave further comments.

**Comment by eldruin** [comment]
Thank you for your summary @jamesmunns. I was not aware of the whole situation/misunderstood it.
Your work is nevertheless much appreciated @adamhott. Please feel encouraged to continue.

**Pull request closed without merging**
