### PR TITLE
add team risc-v e-mail address

### PR DESCRIPTION
**Pull request by japaric**
r? @rust-embedded/riscv

### CODE REVIEW

**Comment by japaric** [comment]
By the way, I just realized that the e-mail address (risc-v@) and the team name (riscv) on GH don't match.

**Comment by Disasm** [comment]
@japaric 
Yes, because team name is incorrect. See: https://riscv.org/risc-v-trademark-usage/

**Comment by Disasm** [comment]
Also, I'm OK with `riscv` spelling in "technical" things like crate names, emails and URLs, but not with the human-readable names where `RISCV` spelling is used.

**Comment by japaric** [comment]
bors=disasm

@Disasm should I rename the team then? There may be some breakage in .github/CODEOWNERS

**Comment by Disasm** [comment]
@japaric if you can just change human-readable name from `RISCV` to `RISC-V`, it will be good. There should be no problems with CODEOWNERS if we leave `rust-embedded/riscv` internal name.

**Comment by japaric** [comment]
bors r=disasm

@disasm AFAICT changing the human facing name to "RISC-V" changes the mention name to risc-v

**Comment by Disasm** [comment]
@japaric Ok, then I suggest to leave this name as it is. It's not worth breaking the infrastructure :)

**Comment by Disasm** [comment]
bors r+
Please!

**Comment by japaric** [comment]
IDK what's wrong with bors it has been misbehaving in my personal repos.

The Travis build is [green](https://travis-ci.org/rust-embedded/wg/builds/489691353) (it's always green, actually ;-)), so I'm going to merge this manually.

**Comment by Disasm** [comment]
Looks like I'm in RISC-V team, but not in All team, so "Permission denied" is not a bug. However, your `r?` should change the reviewer, but doesn't.

**Comment by japaric** [comment]
@Disasm whoops, fixed.

"r?" does nothing because we are not using rust-highfive (yet).

**Pull request merged**
