### PR TITLE
add e-mail addresses for the teams

### PR DESCRIPTION
**Pull request by japaric**
This a proposal to give each team an e-mail address. As discussed in the last
meeting we'll be using the `team-name@teams.rust-embedded.org` format for the
e-mail addresses.

This proposal (PR) needs at least 10 votes (approvals) from @rust-embedded/all
to be accepted. After the proposal has been accepted we'll proceed to implement
it.

@rust-embedded/all please vote on this proposal using [pull request reviews].
Or if you have a concern leave a comment.

[pull request reviews]: https://help.github.com/articles/about-pull-request-reviews/

### CODE REVIEW

**Comment by japaric** [comment]
10 people have approved this proposal so I'm going to mark it as "accepted".

Before we land this PR we need to implement the e-mail aliases but I believe that's blocked on updating the DNS infrastructure (#156) so I'm going to mark this as blocked for now. cc @nastevens

**Comment by nastevens** [comment]
Initial changes are up for DNS infrastructure (https://github.com/rust-embedded/wg/issues/156) so we can start thinking about this again. I have not personally set up mailing list infrastructure before - is there anyone with experience in this that can work with me?

**Comment by japaric** [comment]
@ryankurte mentioned in #153 that they have experience setting up mail aliases using mailgun.

**Comment by ryankurte** [comment]
Yep! The mailgun add-domain stuff should get you most of the way there, then I just add routes for each address. Can check your work here or via email if you would like, and let me know if you need any more help?

**Comment by nastevens** [comment]
@ryankurte - If you're able to take a look at #156 that gets the base DNS terraform config set up. From there it should be straightforward to add the `teams` subdomain and appropriate MX records to make the lists happen.

**Comment by japaric** [comment]
@rust-embedded/infrastructure now that the DNS stuff has been sorted out, any chance you could look into setting up the e-mail aliases?

**Comment by japaric** [comment]
The infra team is currently setting up the team e-mails!

I have updated this PR to list only the team e-mails that are in place. That way we can land this PR now and then add the other e-mails in follow-up PRs.

r? anyone

**Pull request merged**
